# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET and Python Tests

on:
  push:
    branches: 
      - "C#-Cargohub"
  pull_request:
    branches: 
      - "C#-Cargohub"
  

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    # # Run .NET tests
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    
    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.12'
    
    # - name: Install pytest
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install pytest
    
    # - name: Run pytest tests
    # # -v for more detailed output (easier debugging)
    #   run: pytest ./Integrationtests/endpoints_tests.py -v

    - name: Update SERVER and restart
      run: |

        # Kill previous dotnet programs
        pkill -f 'dotnet run' || true
      
        # Navigate to the persistent directory
        mkdir -p ~/persistent-dir/Cargohub-Inf2
      
        cd ~/persistent-dir/Cargohub-Inf2
      
        # Initialize git repo if not already initialized
        if [ ! -d ".git" ]; then
          git init
          git remote add origin https://github.com/HamsterChief/Cargohub-Inf2.git
        fi
      
        # Fetch the branch and reset to ensure synchronization
        git fetch origin "C#-Cargohub"
        git reset --hard origin/"C#-Cargohub"

        # Change to the project directory
        cd ~/persistent-dir/Cargohub-Inf2/MyEFCoreProject
      
        # Start the application in the background with nohup
        nohup dotnet run --urls "http://0.0.0.0:5072" > ~/persistent-dir/output.log 2>&1 &
      
        # Check running processes and ports
        ps aux | grep 'dotnet'