# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET and Python Tests

on:
  push:
    branches: 
      - "C#-Cargohub"
  pull_request:
    branches: 
      - "C#-Cargohub"
  

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    # # Run .NET tests
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    
    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.12'
    
    # - name: Install pytest
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install pytest
    
    # - name: Run pytest tests
    # # -v for more detailed output (easier debugging)
    #   run: pytest ./Integrationtests/endpoints_tests.py -v

    # Step to pull the latest code from Git
    - name: Pull Latest Changes from Git
      run: |
        cd ~/persistent-dir/Cargohub-Inf2
        git fetch origin C#-Cargohub
        git reset --hard origin/C#-Cargohub

    # Step to restart the service after pulling the latest code
    - name: Restart EF Core Project Service
      run: |
        sudo systemctl restart myefcoreproject
        sudo systemctl status myefcoreproject  # Verify it's running