# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET and Python Tests

on:
  push:
    branches: 
      - "C#-Cargohub"
  pull_request:
    branches: 
      - "C#-Cargohub"
  workflow_dispatch: # Allows manual triggering

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    # FOR NOW not needed when integration tests in C# are finished
    # # Run .NET tests
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    
    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.12'
    
    # - name: Install pytest
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install pytest
    
    # - name: Run pytest tests
    # # -v for more detailed output (easier debugging)
    #   run: pytest ./Integrationtests/endpoints_tests.py -v

    - name: Connect to SSH Server and Run Commands
      run: |
            cd $GITHUB_WORKSPACE
            git reset --hard HEAD
            git pull origin C#-Cargohub
            cd MyEFCoreProject
            dotnet build

            # Check if the server is already running using tmux
            if ! tmux has-session -t dotnet_server 2>/dev/null; then
                echo "Starting new server session..."
                # Start the server in a new tmux session
                tmux new-session -d -s dotnet_server "dotnet run --urls http://0.0.0.0:5072"
            else
                echo "Server is already running. Skipping restart."
            fi

            # Detach the tmux session to keep the server running
            tmux detach -s dotnet_server

            # Optionally, verify tmux session is still running
            tmux list-sessions