# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET and Python Tests

on:
  push:
    branches: 
      - "C#-Cargohub"
  pull_request:
    branches: 
      - "C#-Cargohub"
  

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    # # Run .NET tests
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    

    # Step to pull the latest code from Git
    - name: Pull Latest Changes from Git
      run: |
        cd ~/persistent-dir/Cargohub-Inf2
        git fetch origin C#-Cargohub
        git reset --hard origin/C#-Cargohub

    - name: Backup appsettings.json
      run: |
        cp ~/persistent-dir/Cargohub-Inf2/appsettings.json ~/persistent-dir/Cargohub-Inf2/appsettings.json.bak

    - name: Update appsettings.json for Test Database
      run: |
        sed -i 's|"sqlite": "Data Source=cargohub_database.db"|"sqlite": "Data Source=cargohub_Test_database.db"|' ~/persistent-dir/Cargohub-Inf2/appsettings.json

    #restart so it uses the updated appsettings.json
    - name: Restart EF Core Project Service
      run: |
        echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl restart myefcoreproject
        sudo systemctl status myefcoreproject  # Verify it's running

    - name: Check Current Directory
      run: pwd

    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.12'
    
    # - name: Install pytest
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install pytest
    
    # - name: Run pytest tests
    # # -v for more detailed output (easier debugging)
    #   run: pytest ./Integrationtests/endpoints_tests.py -v
    # Run your tests (replace with your actual tests)


    - name: Restore Original appsettings.json
      run: |
        mv ~/persistent-dir/Cargohub-Inf2/appsettings.json.bak ~/persistent-dir/Cargohub-Inf2/appsettings.json

    # Restart the service to restore original appsettings
    - name: Restart EF Core Project Service with Original Configuration
      run: |
        echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl restart myefcoreproject
        sudo systemctl status myefcoreproject  # Verify it's running